apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: frontend-test
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argocd-applicationset-demo.git
        targetRevision: HEAD
        path: cluster-generator-singleC--singleN/frontend 
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
